export const signStateKey = {
  SIGNIN: "SIGNIN", SIGNUP: "SIGNUP"
}

export const TOAST_POSITION = {
  TOP_RIGHT: "topRight",
}

export const USER_ROLE = {
  ADMIN: "ADMIN",
  PARENT: "PARENT",
  STUDENT: "STUDENT",
  TEACHER: "TEACHER",
  BACKOFFICEUPLOADER: "BACKOFFICEUPLOADER",
  BACKOFFICEREVIEWER: "BACKOFFICEREVIEWER",
}

export const USER_ROLE_HUMAN_FRIENDLY = {
  ADMIN: "Admin",
  PARENT: "Parent",
  STUDENT: "Student",
  TEACHER: "Teacher",
  BACKOFFICEUPLOADER: "Uploader",
  BACKOFFICEREVIEWER: "Reviewer",
}

export const USER_ROLE_HUMAN_FRIENDLY_SMALL_CASE = {
  ADMIN: "admin",
  PARENT: "parent",
  STUDENT: "student",
  TEACHER: "teacher",
  BACKOFFICEUPLOADER: "uploader",
  BACKOFFICEREVIEWER: "reviewer",
}

export const USER_ROLE_TYPE = {
  NORMAL: "NORMAL",
  BACKOFFICE: "BACKOFFICE",
  ADMIN: "ADMIN",
}

export const USER_STATUS = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
}

export const DEFAULT_TEACHER_ID = 332;

export const ERROR_STATE_STRING = 'ERROR_STATE_STRING'

// Routes based on url
export const NORMAL_LOGIN_URL = "/auth/login";
export const NORMAL_SIGNUP_URL = "/auth/login";
export const LOGOUT_REDIRECT_URL = "/";

export const SIGNIN_VIEW = "/app/welcome";

// LOCAL STORAGE KEYS
export const LOCAL_STORAGE_KEYS = {
  AUTHORIZATION: "Authorization",
  GOOGLE_DRIVE_AUTHORIZATION: "GOOGLE_DRIVE_AUTHORIZATION",
  GOOGLE_DRIVE_REFRESH: "GOOGLE_DRIVE_REFRESH",
  ROLE: "ROLE",
  GOOGLE_DRIVE_AUTHORIZATION_DATE: "GOOGLE_DRIVE_AUTHORIZATION_DATE",
  GOOGLE_DRIVE_AUTHORIZATION_TIME: "GOOGLE_DRIVE_AUTHORIZATION_TIME",
}

// LOCAL FORAGE KEYS
export const LOCAL_FORAGE_KEYS = {
  EXAMID: "EXAMID",
  TEACHERID: "TEACHERID",
  QUESTIONSTOFETCH: "QUESTIONSTOFETCH",
}

export const QUESTION_STATUS = {
  PENDING: "PENDING",
  CREATED: "CREATED",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
}

export const QUESTION_TYPE = {
  QUESTION: "QUESTION",
  MCQ_2OPTIONS: "MCQ_2OPTIONS",
  MCQ_3OPTIONS: "MCQ_3OPTIONS",
  MCQ_4OPTIONS: "MCQ_4OPTIONS",
  MCQ_5OPTIONS: "MCQ_5OPTIONS",
}

export const QUESTION_DIFFICULTY = {
  DFFICULT: 3,
  MEDIUM: 2,
  EASY: 1
}

export const INTEGER_DIFFICULTY = {
  3: "DFFICULT",
  2: "MEDIUM",
  1: "EASY"
}

export const MODAL_ROUTE_MESSAGE = {
  LESSON_EDIT_MODAL: "LESSON_EDIT_MODAL",
  LESSON_ADD_MODAL: "LESSON_ADD_MODAL",
  LESSON_VIDEO_MODAL: "LESSON_VIDEO_MODAL",
  QUESTION_EDIT_MODAL: "QUESTION_EDIT_MODAL",
  QUESTION_ADD_MODAL: "QUESTION_ADD_MODAL",
  EXAM_PAY_TO_VIEW_MODAL: "EXAM_PAY_TO_VIEW_MODAL",
  SUBMIT_EXAM_CONFIRM: "SUBMIT_EXAM_CONFIRM",
}

export const RESULT_TYPE_BACKEND = {
  CORRECT: "CORRECT", 
  STUDENT_NO_ANSWER: "STUDENT_NO_ANSWER", 
  WRONG: "WRONG", 
  EXAMINER_NO_ANSWER: "EXAMINER_NO_ANSWER",
}


export const MCQ_KEYS_LIST = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'];

export const POPUP_CLOSE_URL = "http://localhost:3000/closePopup"